clusterName: demo-eks
region: eu-central-1
vpcId: vpc-0f25f0b7d23e23a3f # change this

serviceAccount:
  create: false
  name: aws-load-balancer-controller

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
