clusterName: demo-eks
region: eu-central-1
vpcId: vpc-0f3d8e75a93d1a4eb

serviceAccount:
  create: false
  name: aws-load-balancer-controller

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
