apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: demo-app-manual
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: demo-app-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:eu-central-1:398934906881:secret:rds!db-78f33f3e-12ed-46c8-a14f-2bcd76c60795-FUluj0
        property: password
