apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: demo-app-argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: demo-app-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:eu-central-1:398934906881:secret:rds!db-b9658441-d942-4a66-b774-4ee532c9ba69-C8AWNe
        property: password
